DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 256
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 8
OPTIM:
  NAME: adam
  LR: 0.0001
  MAX_EPOCH: 10
  LR_SCHEDULER: cosine
  WARMUP_EPOCH: 1
  WARMUP_TYPE: constant
  WARMUP_CONS_LR: 1e-05
TRAIN:
  PRINT_FREQ: 5
